### ISSUE TITLE
Class / ID for custom CSS

### ISSUE THREAD

**Issue by sujaypawar** [brainstormforce/fullwidth-templates#4]
Is there any CSS Class / ID predefined in the templates we're adding for extra CSS customizations?

**Comment by Nikschavan** [comment]
WordPress adds the current template to the body so we can add css specific for the template, we are also adding the [current theme name](https://github.com/brainstormforce/fullwidth-templates/blob/master/class-fullwidth-page-templates.php#L44) to <body> as a class name, so that can also be used to write theme specific CSS.
